# Generated by Django 4.1.1 on 2022-11-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.CharField(max_length=150)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=3000)),
            ],
        ),
    ]
