# Generated by Django 4.1.1 on 2022-11-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApi', '0003_contactmessage_alter_post_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='id',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
